parameters:
    # entity class
    biddy.entity.core.wallet.class: Biddy\Entity\Core\Wallet
    # form class
    biddy.form.type.core.wallet.class: Biddy\Form\Type\WalletFormType

services:
    biddy_api.handler.wallet:
        class: Biddy\Handler\HandlerInterface
        factory:
            - '@biddy.handler.handler_manager.wallet'
            - 'getHandler'
        arguments:
            - '@biddy.user_role'

    biddy.repository.wallet:
        class: Biddy\Repository\Core\WalletRepository
        factory:
            - '@doctrine.orm.entity_manager'
            - 'getRepository'
        arguments:
            - '%biddy.entity.core.wallet.class%'

    biddy.domain_manager.wallet:
        class: Biddy\DomainManager\WalletManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@biddy.repository.wallet'

    biddy.form.type.wallet:
        class: '%biddy.form.type.core.wallet.class%'
        wallets:
            - { name: form.type, alias: biddy_form_wallet }

    biddy.handler.handlers.wallet.abstract:
        class: Biddy\Handler\Handlers\Core\WalletHandlerAbstract
        parent: biddy.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - '%biddy.form.type.core.wallet.class%'
            - '@biddy.domain_manager.wallet'

    biddy.handler.handlers.wallet.admin:
        class: Biddy\Handler\Handlers\Core\Admin\WalletHandler
        parent: biddy.handler.handlers.wallet.abstract
        public: false
        arguments:
            - '@biddy_user.domain_manager.account'

    biddy.handler.handlers.wallet.sale:
        class: Biddy\Handler\Handlers\Core\Sale\WalletHandler
        parent: biddy.handler.handlers.wallet.abstract
        public: false
        arguments:
            - '@biddy_user.domain_manager.account'

    biddy.handler.handlers.wallet.account:
        class: Biddy\Handler\Handlers\Core\Account\WalletHandler
        parent: biddy.handler.handlers.wallet.abstract
        public: false

    biddy.handler.handler_manager.wallet:
        class: Biddy\Handler\HandlerManager
        arguments:
            - '%biddy.entity.core.wallet.class%'
            -
                - '@biddy.handler.handlers.wallet.admin'
                - '@biddy.handler.handlers.wallet.sale'
                - '@biddy.handler.handlers.wallet.account'