parameters:
    # entity class
    biddy.entity.core.bill.class: Biddy\Entity\Core\Bill
    # form class
    biddy.form.type.core.bill.class: Biddy\Form\Type\BillFormType

services:
    biddy_api.handler.bill:
        class: Biddy\Handler\HandlerInterface
        factory:
            - '@biddy.handler.handler_manager.bill'
            - 'getHandler'
        arguments:
            - '@biddy.user_role'

    biddy.repository.bill:
        class: Biddy\Repository\Core\BillRepository
        factory:
            - '@doctrine.orm.entity_manager'
            - 'getRepository'
        arguments:
            - '%biddy.entity.core.bill.class%'

    biddy.domain_manager.bill:
        class: Biddy\DomainManager\BillManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@biddy.repository.bill'

    biddy.form.type.bill:
        class: '%biddy.form.type.core.bill.class%'
        tags:
            - { name: form.type, alias: biddy_form_bill }

    biddy.handler.handlers.bill.abstract:
        class: Biddy\Handler\Handlers\Core\BillHandlerAbstract
        parent: biddy.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - '%biddy.form.type.core.bill.class%'
            - '@biddy.domain_manager.bill'

    biddy.handler.handlers.bill.admin:
        class: Biddy\Handler\Handlers\Core\Admin\BillHandler
        parent: biddy.handler.handlers.bill.abstract
        public: false
        arguments:
            - '@biddy_user.domain_manager.account'

    biddy.handler.handlers.bill.sale:
        class: Biddy\Handler\Handlers\Core\Sale\BillHandler
        parent: biddy.handler.handlers.bill.abstract
        public: false
        arguments:
            - '@biddy_user.domain_manager.account'

    biddy.handler.handlers.bill.account:
        class: Biddy\Handler\Handlers\Core\Account\BillHandler
        parent: biddy.handler.handlers.bill.abstract
        public: false

    biddy.handler.handler_manager.bill:
        class: Biddy\Handler\HandlerManager
        arguments:
            - '%biddy.entity.core.bill.class%'
            -
                - '@biddy.handler.handlers.bill.admin'
                - '@biddy.handler.handlers.bill.sale'
                - '@biddy.handler.handlers.bill.account'