parameters:
    # entity class
    biddy.entity.core.credit_transaction.class: Biddy\Entity\Core\CreditTransaction
    # form class
    biddy.form.type.core.credit_transaction.class: Biddy\Form\Type\CreditTransactionFormType

services:
    biddy_api.handler.credit_transaction:
        class: Biddy\Handler\HandlerInterface
        factory:
            - '@biddy.handler.handler_manager.credit_transaction'
            - 'getHandler'
        arguments:
            - '@biddy.user_role'

    biddy.repository.credit_transaction:
        class: Biddy\Repository\Core\CreditTransactionRepository
        factory:
            - '@doctrine.orm.entity_manager'
            - 'getRepository'
        arguments:
            - '%biddy.entity.core.credit_transaction.class%'

    biddy.domain_manager.credit_transaction:
        class: Biddy\DomainManager\CreditTransactionManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@biddy.repository.credit_transaction'

    biddy.form.type.credit_transaction:
        class: '%biddy.form.type.core.credit_transaction.class%'
        arguments:
            - '%credit_transaction.amount_not_set%'
            - '%credit_transaction.invalid_amount%'
            - '%credit_transaction.not_enough_credit%'
            - '%credit_transaction.wallet_not_exist%'
        tags:
            - { name: form.type, alias: biddy_form_credit_transaction }

    biddy.handler.handlers.credit_transaction.abstract:
        class: Biddy\Handler\Handlers\Core\CreditTransactionHandlerAbstract
        parent: biddy.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - '%biddy.form.type.core.credit_transaction.class%'
            - '@biddy.domain_manager.credit_transaction'

    biddy.handler.handlers.credit_transaction.admin:
        class: Biddy\Handler\Handlers\Core\Admin\CreditTransactionHandler
        parent: biddy.handler.handlers.credit_transaction.abstract
        public: false
        arguments:
            - '@biddy_user.domain_manager.account'

    biddy.handler.handlers.credit_transaction.sale:
        class: Biddy\Handler\Handlers\Core\Sale\CreditTransactionHandler
        parent: biddy.handler.handlers.credit_transaction.abstract
        public: false
        arguments:
            - '@biddy_user.domain_manager.account'

    biddy.handler.handlers.credit_transaction.account:
        class: Biddy\Handler\Handlers\Core\Account\CreditTransactionHandler
        parent: biddy.handler.handlers.credit_transaction.abstract
        public: false

    biddy.handler.handler_manager.credit_transaction:
        class: Biddy\Handler\HandlerManager
        arguments:
            - '%biddy.entity.core.credit_transaction.class%'
            -
                - '@biddy.handler.handlers.credit_transaction.admin'
                - '@biddy.handler.handlers.credit_transaction.sale'
                - '@biddy.handler.handlers.credit_transaction.account'