Biddy\Entity\Core\ProductRating:
    type: entity
    table: core_product_rating
    repositoryClass: Biddy\Repository\Core\ProductRatingRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        deletedAt:
            type: date
            nullable: true
        createdDate:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        rateValue:
            type: float
            options:
                default: 1
            nullable: true
        rateMessage:
            type: text
            nullable: true
    manyToOne:
        reviewer:
            targetEntity: Biddy\Bundle\UserSystem\AccountBundle\Entity\User
        product:
            targetEntity: Biddy\Entity\Core\Product
            inversedBy: productRatings
        bill:
            targetEntity: Biddy\Entity\Core\Bill
            inversedBy: productRatings