parameters:
    # https://github.com/schmittjoh/JMSSerializerBundle/pull/270
    # not really happy about doing this, but there is no proper config
    # for setting camelcase, so we overwrite the default naming strategy here to match the name
    # of the property in the php class
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy


    # event dispatched on user action such as add, remove, delete
    biddy.events.handler_event: 'biddy.events.handler_event'

services:
    biddy.service.console_output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    biddy.handler.handler_abstract:
        class: Biddy\Handler\HandlerAbstract
        abstract: true
        public: false
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
            - [setEvent, ['%biddy.events.handler_event%']]

    biddy.service.date_util:
        class: Biddy\Service\Util\DateUtil

    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.user%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor }

    monolog.processor.session_request:
        class: Biddy\Bundle\ApiBundle\Service\SessionRequestProcessor
        arguments:
            - '@security.token_storage'
        tags:
            - { name: monolog.processor, method: processRecord }

    # new worker design ----------------------------------------------------------------------------------

    biddy.redis.app_cache:
        class: Redis
        calls:
            - [connect, ["%biddy.redis.app_cache.host%","%biddy.redis.app_cache.port%"]]

    ### linear worker pool

    ### end of concurrence worker pool

    # end of new worker design ---------------------------------------------------------------------------

    # TODO: change...
    fos_user.change_password.form.type:
        class: FOS\UserBundle\Form\Type\ChangePasswordFormType
        arguments:
            - '%fos_user.model.user.class%'

    # TODO: change...
    fos_user.group.form.type:
        class: FOS\UserBundle\Form\Type\GroupFormType
        arguments:
            - '%fos_user.model.group.class%'

    # TODO: change...
    fos_user.profile.form.type:
        class: FOS\UserBundle\Form\Type\ProfileFormType
        arguments:
            - '%fos_user.model.user.class%'

    # TODO: change...
    fos_user.registration.form.type:
        class: FOS\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - '%fos_user.model.user.class%'

    # TODO: change...
    fos_user.resetting.form.type:
        class: FOS\UserBundle\Form\Type\ResettingFormType
        arguments:
            - '%fos_user.model.user.class%'


