Biddy\Entity\Core\Task:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [task.detail, task.summary]
        project:
            expose: true
            groups: [task.detail, task.summary]
        board:
            expose: true
            groups: [task.detail, task.summary]
        cardNumber:
            expose: true
            groups: [task.detail, task.summary]
        createdDate:
            expose: true
            groups: [task.detail, task.summary]
        status:
            expose: true
            groups: [task.detail, task.summary]
        releasePlan:
            expose: true
            groups: [task.summary]
        review:
            expose: true
            groups: [task.detail, task.summary]
        targetType:
            expose: true
            groups: [task.detail, task.summary]
        targetId:
            expose: true
            groups: [task.detail, task.summary]