parameters:
    biddy_sale_api.form.type.user.class: Biddy\Bundle\SaleApiBundle\Form\Type\UserFormType

services:
    # main public services

    biddy_sale_api.handler.user:
        class: Biddy\Bundle\SaleApiBundle\Handler\UserHandler
        parent: biddy.handler.handler_abstract
        public: true
        arguments:
            - '@form.factory'
            - '%biddy_sale_api.form.type.user.class%'
            - '@biddy_user.domain_manager.account'

    # forms

    biddy_sale_api.form.type.user:
        class: Biddy\Bundle\SaleApiBundle\Form\Type\UserFormType
        arguments:
            - "@=service('security.helper').getToken().getUser()"
            - "@biddy_user.domain_manager.account"
            - "%user_register_duplicate_email%"
            - "%user_register_duplicate_username%"
            - "%user_register_duplicate_phone%"
        tags:
            - { name: form.type, alias: biddy_form_sale_api_user }

    biddy_sale_api.event_listener.set_account_uuid_listener:
        class: Biddy\Bundle\SaleApiBundle\EventListener\SetAccountUuidListener
        tags:
            - { name: doctrine.event_listener, event: prePersist}