
biddy_user_system_sale_profile_show:
    path: /
    defaults: { _controller: "FOSUserBundle:Profile:show" }
    methods: "GET"

biddy_user_system_sale_profile_edit:
    path: /edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }