imports:
    - { resource: services/services.yml }
    - { resource: services/service.worker.yml }
    - { resource: services/service.listener.yml}
    - { resource: services/service.voter.yml }
    - { resource: services/service.alert.yml }
    - { resource: services/service.task.yml }
    - { resource: services/service.product.yml }
    - { resource: services/service.bid.yml }
    - { resource: services/service.bill.yml }
    - { resource: services/service.product_view.yml }
    - { resource: services/service.comment.yml }
    - { resource: services/service.reaction.yml }
    - { resource: services/service.tag.yml }
    - { resource: services/service.product_tag.yml }
    - { resource: services/service.product_rating.yml }
    - { resource: services/service.credit_transaction.yml }
    - { resource: services/service.auction.yml }
    - { resource: services/service.wallet.yml }
    - { resource: product/service.freelancer.yml }
    - { resource: product/service.professional.yml }

parameters:
    # jwt
    biddy_api.service.jwt_response_transformer.class: Biddy\Bundle\ApiBundle\Service\JWTResponseTransformer
    biddy.event.authentication_success_listener.class: Biddy\Bundle\ApiBundle\EventListener\AuthenticationSuccessListener
    biddy.event.jwt_created_listener.class: Biddy\Bundle\ApiBundle\EventListener\JWTCreatedListener

services:
    # handlers
    biddy.handler.role_handler_abstract:
        class: Biddy\Handler\RoleHandlerAbstract
        abstract: true
        public: false
        parent : biddy.handler.handler_abstract
        arguments:
            - '@form.factory'

    # authentication
    biddy_api.service.jwt_response_transformer:
        class: '%biddy_api.service.jwt_response_transformer.class%'

    biddy.event.authentication_success_listener:
        class: '%biddy.event.authentication_success_listener.class%'
        arguments: ['@biddy_api.service.jwt_response_transformer', '@fos_user.user_manager']
        tags:
            -
               name: kernel.event_listener
               event: 'lexik_jwt_authentication.on_authentication_success'
               method: 'onAuthenticationSuccess'
               priority: 10

    biddy.event.jwt_created_listener:
        class: '%biddy.event.jwt_created_listener.class%'
        tags:
            -
                name: kernel.event_listener
                event: 'lexik_jwt_authentication.on_jwt_created'
                method: 'onJWTCreated'

    biddy_api.mailer.mailer:
        class: Biddy\Bundle\ApiBundle\Mailer\Mailer
        arguments:
            - '@mailer'
            - '@router'
            - '@templating'
            -
                resetting.template: BiddyApiBundle:Resetting:email.txt.twig
                from_email:
                    resetting: '%biddy_user_system_account.resetting.email.from_email%'
                password_resetting_link: '%password_resetting_link%'