parameters:
    biddy.bundle.user.entity.user.class: Biddy\Bundle\UserBundle\Entity\User
    # define user systems
    biddy.user_system.account: biddy_user_system_account
    biddy.user_system.admin: biddy_user_system_admin
    # event dispatched on login success
    biddy_user.events.login_success: biddy_user.events.login_success
    # used in \Biddy\Bundle\UserBundle\DependencyInjection\Compiler\OverrideServiceCompilerPass
    biddy_user.request.user_system.authentication_listener.class: Biddy\Bundle\UserBundle\Request\UserSystem\AuthenticationListener

services:
    # returns our role model class for the current authenticated user entity
    biddy.token:
        class: Symfony\Component\Security\Core\Authentication\Token\TokenInterface
        factory:
            - '@security.helper'
            - 'getToken'

    biddy.user_role:
        class: Biddy\Model\User\Role\UserRoleInterface
        factory:
            - '@biddy.token'
            - 'getUser'

    biddy_user.domain_manager.admin:
        class: Biddy\Bundle\UserBundle\DomainManager\AdminManager
        arguments:
            - '@biddy_user_system_admin.user_manager'

    biddy_user.domain_manager.account:
        class: Biddy\Bundle\UserBundle\DomainManager\AccountManager
        arguments:
            - '@biddy_user_system_account.user_manager'

    biddy_user.domain_manager.sale:
        class: Biddy\Bundle\UserBundle\DomainManager\SaleManager
        arguments:
            - '@biddy_user_system_sale.user_manager'

    biddy_user.handler.authentication_success:
        class: Biddy\Bundle\UserBundle\Handler\AuthenticationSuccessHandler
        arguments:
            - '@lexik_jwt_authentication.handler.authentication_success'
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
            - [setSuccessEventName, ["%biddy_user.events.login_success%"]]

    biddy_user.request.user_system.request_matcher:
        class: Biddy\Bundle\UserBundle\Request\UserSystem\RequestMatcher

    biddy_app.event_listener.user_type_security_listener:
        class: Biddy\Bundle\UserBundle\EventListener\UserTypeSecurityListener
        arguments:
            - '@security.helper'
            - '@annotation_reader'

        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }